# Generated by Django 5.2.16 on 2026-07-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintBurndownSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_points', models.PositiveIntegerField(default=0)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_snapshots', to='projects.sprint')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('sprint', 'date'), name='unique_sprint_burndown_date')],
            },
        ),
    ]
