# Generated by Django 5.2.16 on 2026-07-31 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuecomment_commentmention_notification_and_more'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('date', 'Date'), ('user', 'User picker'), ('multi_select', 'Multi-select')], max_length=16)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IssueCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='issues.customfield')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='SavedIssueFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('jql', models.CharField(blank=True, max_length=1000)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_issue_filters', to='workspaces.workspacemembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_custom_field_key_per_project'),
        ),
        migrations.AddIndex(
            model_name='issuecustomfieldvalue',
            index=models.Index(fields=['field', 'issue'], name='custom_value_field_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuecustomfieldvalue',
            constraint=models.UniqueConstraint(fields=('issue', 'field'), name='unique_issue_custom_field_value'),
        ),
        migrations.AddConstraint(
            model_name='savedissuefilter',
            constraint=models.UniqueConstraint(fields=('project', 'owner', 'name'), name='unique_saved_filter_name_per_owner'),
        ),
    ]
