# Generated by Django 5.2.16 on 2026-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_customfield_issuecustomfieldvalue_savedissuefilter_and_more'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='board_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status', 'board_order'], name='issue_board_order_idx'),
        ),
    ]
