# Generated by Django 5.2.16 on 2026-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_board_order_issue_issue_board_order_idx'),
        ('projects', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.sprint'),
        ),
    ]
