# Generated by Django 5.2.16 on 2026-07-31 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_sprint'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seconds_spent', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to='workspaces.workspacemembership')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='issues.issue')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['issue', 'started_at'], name='worklog_issue_started_idx')],
            },
        ),
    ]
