# Generated by Django 5.2.16 on 2026-07-31 12:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, and single hyphens only.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('project_lead', 'Project lead'), ('developer', 'Developer'), ('viewer', 'Viewer'), ('external_client', 'External client')], default='viewer', max_length=24)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'role'], name='workspace_role_idx'), models.Index(fields=['user', 'workspace'], name='user_workspace_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership')],
            },
        ),
    ]
